name: Generate Card

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate card image
      run: |
        # Make sure the OC_TOKEN environment variable is available
        export OC_TOKEN=${{ secrets.OC_TOKEN }}
        python gen.py
    
    - name: Set RELEASE_TAG
      id: release_tag
      run: |
        # Attempt to get the latest tag
        RELEASE_TAG=$(git describe --tags --abbrev=0 || echo "latest")
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
    
    - name: Upload to GitHub Release
      if: success()
      run: |
        gh release upload ${{ env.RELEASE_TAG }} ./card.svg --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

