name: Generate Card

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate card image
      run: |
        # Make sure the OC_TOKEN environment variable is available
        export OC_TOKEN=${{ secrets.OC_TOKEN }}
        python gen.py

    - name: Upload SVG to GitHub Repo
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const path = './card.svg';
          const content = fs.readFileSync(path, { encoding: 'base64' });
          const owner = process.env.GITHUB_ACTOR;
          const repo = process.env.GITHUB_REPOSITORY.split('/')[1];
          const filePath = 'card.svg';
          await github.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: filePath,
            message: 'Upload SVG Card',
            content,
            committer: {
              name: 'GitHub Actions',
              email: 'actions@github.com'
            }
          });

    - name: Generate Camo URL
      run: |
        echo "https://raw.githubusercontent.com/${GITHUB_ACTOR}/${GITHUB_REPOSITORY}/refs/heads/main/card.svg"
